sky-uk/kfp-operator

Dockerfile, argo/events/Dockerfile, argo/events/go.mod, argo/events/go.sum, go.mod, go.sum
Go 1.18 is required for upcoming work including #67.
This change is backwards compatible and no other changes are needed. It'll also allow the introduction of generics.
=> Upgrade Go to 1.18

config/testing/integration-test-values.yaml
https://github.com/sky-uk/kfp-operator/pull/158 has changed the default `containerRegistry` value, resulting in the integration tests failing as they were trying to pull all images.
=> Fix integration tests by using local container images

Makefile, apis/common_types.go, apis/config/v1alpha2/kfp_controller_config_types.go, apis/config/v1alpha2/zz_generated.deepcopy.go, config/crd/bases/config.kubeflow.org_kfpcontrollerconfigs.yaml, config/crd/bases/pipelines.kubeflow.org_pipelines.yaml, config/crd/bases/pipelines.kubeflow.org_runconfigurations.yaml, helm/kfp-operator/templates/crd/bases/config.kubeflow.org_kfpcontrollerconfigs.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_pipelines.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runconfigurations.yaml
After conversion from v1alpha2 to v1alpha3, environment variables and Beam arguments with empty values are serialised as follows:
```yaml
- name: empty value
- name: not empty value
value: something
```
This change forces the serialisation to output the value even when empty:
```yaml
- name: empty value
value: ""
- name: not empty value
value: something
```
=> Force serialisation of name and values in NamedValue

Makefile
The previous installation manifest was not kustomized and, therefore, pointed to `latest` instead of the specified version.
=> Fix version of Argo workflows in integration tests

config/manager/workflows/common.yaml, config/manager/workflows/compiled.yaml, config/manager/workflows/rbac.yaml, config/manager/workflows/simple.yaml, config/testing/integration-test-values.yaml, helm/kfp-operator/templates/workflows/common.yaml, helm/kfp-operator/templates/workflows/compiled.yaml, helm/kfp-operator/templates/workflows/rbac.yaml, helm/kfp-operator/templates/workflows/simple.yaml, helm/kfp-operator/values.yaml
Create a service account to run Argo workflows only when required. It allows operators to choose to create that SA externally.
=> Optionally create Argo service account

argo/providers/vai/eventing_server.go, argo/providers/vai/vai_eventing_server_unit_test.go
The URI is not the location of the pushed model, but the base for pipeline step artifacts (which is present for any pipeline run artifact).
This has been changed to use the `pushed_destination` property instead, which is inline with the KFP equivalent.
=> Change model location for VAI pipeline runs

argo/providers/kfp/metadata_store.go, argo/providers/kfp/metadata_store_unit_test.go
the artifact type `PushedModel` will not be created until the first pipeline run has produced a model. Requests are therefore failing.
Check error responses and don't fail the call when the result is `NotFound`
=> Don't error when no PushedModel Type found

config/manager/workflows/common.yaml, config/manager/workflows/compiled.yaml, config/manager/workflows/simple.yaml, helm/kfp-operator/values.yaml
Remove sencondsAfterSuccess and sencondsAfterFailure and increase sencondsAfterCompletion to allow users to set each field and only keep the fallback option.
=> Change default Workflow TTL

apis/pipelines/v1alpha4/test_generators.go, controllers/pipelines/experiment_workflow_integration_test.go, controllers/pipelines/pipeline_workflow_integration_test.go, controllers/pipelines/run_workflow_integration_test.go, controllers/pipelines/runconfiguration_workflow_integration_test.go, controllers/pipelines/suite_integration_test.go
Since introducing `ObservedPipelineVersion` into the Run Status in https://github.com/sky-uk/kfp-operator/commit/e973f34633e81055eba2271b5e6632ae1725b951, the workflow factory required this field to be present.
This PR adds the field to randomly generated Run resources in the integration tests.
=> Fix failing Run integration tests

controllers/pipelines/runconfiguration_controller.go, controllers/pipelines/runconfiguration_controller_decoupled_test.go
Relates to #213. This is a requrement for migration to the new triggers format. It addresses the following rollback scenario:
1. operator migrated to version that supports v1alpha5 with triggers
2. resource updated by operator not populating the provider ID as part of v1alpha5 (conversion to v1alpha4 would leave it empty) - this would change the provider ID in the RS  
3. operator downgraded to previous version
Without this card, the Provider ID in the RC would be empty and not consistent with the one in the RS, resulting in the operator attempting to create a new schedule on the provider, and setting a new provider ID.
=> Populate RC Provider ID from RS if empty

controllers/pipelines/runconfiguration_controller.go, controllers/pipelines/runconfiguration_controller_decoupled_test.go
Relates to #213
Similar to #223, when the ProviderId is empty, the version should be populated from the RunSchedule to avoid unnecessary updates
=> Populate version in RC if empty

argo/run-completer/run_completer.go, argo/run-completer/suite_decoupled_test.go
Jobs that are not triggered by a one-off run do not contain a namespace in the RunCompletionEvent.
This is a valid scenario and should not fail the workflow.
=> Succeed run completer when no namespace is provided

helm/kfp-operator/templates/webhook_manifests.yaml
This has been forgotten in a previous change.
=> Add custom webhook provider for RC validating webhook

apis/pipelines/v1alpha4/run_conversion.go, apis/pipelines/v1alpha4/run_conversion_test.go, apis/pipelines/v1alpha5/run_conversion.go, apis/pipelines/v1alpha5/runconfiguration_webhook.go
Conversion for runs hadn't been implemented when v1alpha5 was introduced.
=> Implement Run conversion between v1alpha4 and v1alpha5

controllers/pipelines/runconfiguration_controller.go, controllers/pipelines/runconfiguration_controller_decoupled_test.go, controllers/pipelines/utils.go, controllers/pipelines/utils_test.go
The aggregate State of RunConfigurations is calculated only if no sync is currently performed.
A sync is performed by creating missing and deleting excess schedules.
in each iteration, excess schedules are currently marked for deletion.
This PR stops considering schedules marked for deletion as excess schedules any longer.
=> Filter Runschedules marked for deletion

Dockerfile, Makefile, argo/common/test_utils.go, argo/kfp-compiler/Dockerfile, argo/providers/kfp/Dockerfile, argo/providers/kfp/Makefile, argo/providers/stub/Dockerfile, argo/providers/stub/Makefile, argo/providers/vai/Dockerfile, argo/providers/vai/Makefile, argo/run-completer/Dockerfile, argo/run-completer/Makefile, docker-targets.mk
Cross-compile Go binaries outside Docker containers. This speeds up Docker builds and therefore integration tests significantly.
=> Cross-compile Go binaries outside docker builds

argo/common/common_types.go, argo/common/run_completion.go, argo/common/suite_unit_test.go, argo/common/test_utils.go, argo/providers/base/provider.go, argo/providers/kfp/eventing_server.go, argo/providers/kfp/eventing_server_unit_test.go, argo/providers/kfp/kfp_api.go, argo/providers/kfp/kfp_api_unit_test.go, argo/providers/kfp/mock_kfp_api.go, argo/providers/kfp/provider.go, argo/providers/kfp/suite_decoupled_test.go, argo/providers/vai/eventing_server.go, argo/providers/vai/provider.go, argo/providers/vai/vai_eventing_server_unit_test.go, argo/run-completer/suite_decoupled_test.go, controllers/pipelines/run_workflow_factory.go, controllers/pipelines/runschedule_workflow_factory.go, controllers/pipelines/runschedule_workflow_factory_test.go
Closes #248 
- Make RunConfigurationName and PipelineName namespaced in all provider integrations
- Note: v0.3.0 legacy integration is not namespaced
- Add RunId
- Extend NamespacedName:
- make to/from string functions public
- replace JSONMarshaller with TextMarshaller to support YAML (instead od adding YAMLMarshaller)
- add `Empty()` convenvience method
=> RunCompletionEvent changes

Makefile, argo/providers/kfp/Makefile, argo/providers/stub/Makefile, argo/providers/vai/Makefile, argo/run-completer/Makefile
`go build` only linked statically when cross-compiling. Builds on Linux CI machines linked dynamically and produced broken build.
This change unconditionally links all GO binaries statically
=> Link binaries statically to fix cross compilation

helm/kfp-operator/templates/namespace.yaml, helm/kfp-operator/values.yaml
Introduce Helm configuration to allow specifying namespace metadata.
=> Make namespace metadata configurable

argo/status-updater/suite_decoupled_test.go, controllers/pipelines/run_controller_decoupled_test.go, controllers/pipelines/runconfiguration_controller_decoupled_test.go
=> Unflake tests

docker-targets.mk
Always push `latest` in addition to version tags.
=> Push latest tag for all docker images

apis/pipelines/v1alpha5/pipeline_types.go, config/crd/bases/pipelines.kubeflow.org_runconfigurations.yaml, config/crd/bases/pipelines.kubeflow.org_runs.yaml, config/crd/bases/pipelines.kubeflow.org_runschedules.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runconfigurations.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runs.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runschedules.yaml
Pipeline identifiers should support valid kubernetes resource names followed by an optional pipeline version (docker tag followed by hyphen and pipeline hash)
Closes #276
=> Allow valid docker tags in pipeline identifier

argo/providers/vai/eventing_server.go, argo/providers/vai/vai_eventing_server_unit_test.go
Run Completion Events currently contain a `null` value for `servingModelArtifacts` if none is produced. To simplify tooling integration, it is preferrable to have an empty array instead.
From:
```json
{"servingModelArtifacts":null}
```
To:
```json
{"servingModelArtifacts":[]}
```
> [!NOTE]
> Until Go JSON marshalling supports https://github.com/golang/go/issues/27589, initialising a slice is the only way to marshal empty arrays into JSON instead of null values.
=> Initialise ServingModelArtifacts in run completion events

helm/kfp-operator/templates/eventing/status-updater.yaml
Metadata configuration should be applied to all Argo resources consistently
=> Add metadata to status-updater sensor metadata

apis/pipelines/v1alpha5/runconfiguration_types.go, apis/pipelines/v1alpha5/test_generators.go, controllers/pipelines/run_controller_decoupled_test.go, controllers/pipelines/runconfiguration_controller.go, controllers/pipelines/runconfiguration_controller_decoupled_test.go, controllers/pipelines/runconfiguration_controller_test.go, controllers/pipelines/suite_decoupled_test.go
Schedules and Runs should only be created once all dependencies have been met.
This also stabilizes some previously flakey tests
Closes #273
=> Succeed RC when dependencies are not met

argo/providers/get-proto.mk, bibcd.yml
- Uses CI workers with support for [asdf](https://github.com/asdf-vm/asdf)
- Specify `--no-cone` for sparse checkout as this is required for more recent versions of git
=> Use asdf workers

argo/common/common_types.go, argo/common/run_completion.go, argo/common/suite_unit_test.go
The previous version was throwing a PANIC when either RunConfigurationName or RunName were nil.
=> Fix the stringer function of RunCompletionEvent to handle nil pointers

apis/pipelines/utils.go, apis/pipelines/utils_test.go
Adds `FlatMap` and `FlatMapErr` functions for collection utils as shorthands for `Flatten(Map)`
=> Add FlatMap and FlatMapErr

argo/providers/vai/eventing_server.go, argo/providers/vai/provider.go, argo/providers/vai/vai_eventing_server_unit_test.go, controllers/pipelines/run_controller_decoupled_test.go, controllers/pipelines/runconfiguration_controller_decoupled_test.go, controllers/pipelines/runconfiguration_test_helper.go
Fix intermittent decoupled test failures by waiting for state changes before attempting resource updates. We have introduced `runconfiguration_test_helper.go` in order to separate test utilities from actual tests.
Also address `aiplatform` import deprecation warnings.
=> Fix intermittent decoupled test failures

DEVELOPMENT.md, docker-targets.mk
Move to using `CONTAINER_REPOSITORIES` envvar for registry location for image push rather than `CONTAINER_REGISTRY_HOSTS` as this allows to include repository/directories within the registry to be supplied not just list of host names which previous env var indicated.
=> Change to CONTAINER_REPOSITORIES for artifact repository location

argo/kfp-compiler/acceptance/namespaced_pipeline_conf.yaml, argo/kfp-compiler/acceptance/pipeline_conf.yaml, argo/kfp-compiler/acceptance/test_compiler.py, argo/kfp-compiler/kfp_compiler/compiler.py, argo/kfp-compiler/tests/test_compiler.py, argo/providers/base/provider.go, argo/providers/kfp/provider.go, argo/providers/stub/provider.go, argo/providers/vai/config.go, argo/providers/vai/config_unit_test.go, argo/providers/vai/provider.go, argo/providers/vai/provider_unit_test.go, controllers/pipelines/experiment_workflow_integration_test.go, controllers/pipelines/pipeline_workflow_factory.go, controllers/pipelines/pipeline_workflow_factory_test.go, controllers/pipelines/runschedule_workflow_factory.go, controllers/pipelines/suite_integration_test.go
Connects to #40.
Compiler sets pipeline_name which ends up being the pipelineInfo/name in the pipeline definition which is then used in both one off runs and scheduled runs to set the run name.
RunScheduleDefinition and PipelineDefinition Name attribute changed from string (i.e. penguin-pipeline-name) to NamespacedName (i.e. namespace/penguin-pipeline-name) so these values are passed into the relevant workflow.
Changes were needed here because it was found there is currently no way to override the "scheduled run name" (i.e. the name given to individual runs) it just uses the pipelineInfo/name value. A request has been made to Google change the [createSchedule](https://pkg.go.dev/cloud.google.com/go/aiplatform@v1.67.0/apiv1/aiplatformpb#CreateScheduleRequest) interface in the Vertex AI …
=> VAI Provider - Namespaced custom resources for pipelines (scheduled and one off)

argo/kfp-compiler/Dockerfile, argo/providers/stub/Dockerfile
Closes #334 
Updates the Alpine images to the latest version. [`3.20.1` ](https://hub.docker.com/layers/library/alpine/3.20.1/images/sha256-dabf91b69c191a1a0a1628fd6bdd029c0c4018041c7f052870bb13c5a222ae76?context=explore)
=> Update alpine image versions to 3.20.1

argo/kfp-compiler/Dockerfile, argo/providers/stub/Dockerfile
Closes #65
Adds a non-root user to docker images which are currently using a root user. It uses a userid of `65534`  `nobody` for the alpine images.
=> Use `nobody` user in custom alpine docker images

controllers/pipelines/run_workflow_factory.go, controllers/pipelines/runschedule_workflow_factory.go
Closes #337.
Have manually tested creation of new run configuration and it is now successful.
Issue was caused by the namespacing change and the Default experiment not belonging to a namespace.
=> Fix creation of Kubeflow run configuration with no experiment

Makefile, argo/providers/vai/provider.go, argo/providers/vai/provider_unit_test.go
connects to #128 
On deleting a run schedule if Vertex AI responds with NotFound status then ignore the error as nothing to delete.
Without this change the resource was stuck in a "Deleting" status and never recovered.
Have checked with deleting pipelines and they got successfully deleted so no change needed for that.
=> Fix delete run schedule not found with provider VAI

argo/providers/kfp/provider.go, argo/providers/vai/provider.go, argo/providers/vai/provider_unit_test.go
Connects to https://github.com/sky-uk/kfp-operator/issues/128
On deleting a pipeline resource with kubeflow provider when the pipeline didnt actually exist within kubeflow the deletion workflow failed and resource stayed in "deleting" status forever.
This change fixes that. On deleting check error to see if not found if so then ignore.
Refactored existing code in delete run schedule which was doing same logic.
=> Kubeflow Provider - handle NotFound in pipeline resource deletion

argo/providers/vai/provider.go, argo/providers/vai/provider_unit_test.go
Closes #349
```
Name of one off run is now <namespace>-<run definition name (this is the generated name for the run resource)>-<version>
```
e.g. namespace-kfp-operator-quickstart-tvrmk-1564fd
=> Ensure VAI Pipeline Job Id is unique

Makefile, apis/pipelines/v1alpha5/test_generators.go, controllers/pipelines/experiment_controller.go, controllers/pipelines/pipeline_controller.go, controllers/pipelines/reconciler.go, controllers/pipelines/run_controller.go, controllers/pipelines/run_workflow_integration_test.go, controllers/pipelines/runschedule_controller.go, controllers/pipelines/suite_decoupled_test.go, controllers/pipelines/suite_integration_test.go
Links to #329 
Loads the Provider CRD from k8s to be passed through the controllers. Closely related to #353. 
This just adds the behaviour to actually read the provider resource from k8s. Workflows still remain the same.
=> Provider CRD read provider in controllers from k8s

docs-gen/Makefile
Closes #360
within this repo the use of Jekyll to build GH Pages was disabled (as it now explicitly requires GH Actions, that is disabled). As a consequence, the KFP Operator website silently stopped being updated. GH Pages provides instructions to disable the Jekyll build (we didn't need it) and publish the website: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages
`-mindepth 1` was needed as find on linux returns the base directory in the results (i.e. ../docs) which then wasnt empty (as had the .nojekyll) so command failed, mindepth of 1 ensures top level is filtered from the results.
=> Fix GitHub pages nojekyll

helm/kfp-operator/templates/eventing/event-source-webhook.yaml, helm/kfp-operator/templates/eventing/eventsource-webhook.yaml, helm/kfp-operator/templates/eventing/nats-sensor.yaml, helm/kfp-operator/values.yaml, helm/provider/templates/runcompletion/sensor.yaml, helm/provider/values.yaml
Closes https://github.com/sky-uk/kfp-operator/issues/356.
As per the ticket above, we've created a new webhook-based argo EventSource, which along with a new Sensor will publish events to the NATS EventBus. The current Run Completion Event Sensor (which is per-Provider) now sends the event via HTTP through the webhook.
Tested in Vertex AI and Kubeflow Pipelines.
Architecture after this change:
=> Create EventSource Webhook to publish Run Completion Events to eventbus

helm/kfp-operator/templates/deployment.yaml
On trying to deploy realised tabbing on the deployment yaml was out of line causing helm install to fail.
=> Bug - Operator deployment failing

Makefile, config/crd/bases/config.kubeflow.org_kfpcontrollerconfigs.yaml, config/crd/bases/pipelines.kubeflow.org_experiments.yaml, config/crd/bases/pipelines.kubeflow.org_pipelines.yaml, config/crd/bases/pipelines.kubeflow.org_providers.yaml, config/crd/bases/pipelines.kubeflow.org_runconfigurations.yaml, config/crd/bases/pipelines.kubeflow.org_runs.yaml, config/crd/bases/pipelines.kubeflow.org_runschedules.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml, helm/kfp-operator/templates/crd/bases/config.kubeflow.org_kfpcontrollerconfigs.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_experiments.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_pipelines.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_providers.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runconfigurations.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runs.yaml, helm/kfp-operator/templates/crd/bases/pipelines.kubeflow.org_runschedules.yaml, helm/kfp-operator/templates/rbac/role.yaml
links to #358 
In order to utilise more recent gRPC libraries we need to upgrade the version of controller-gen used. It currently is using version 0.4.1 which is many years out of date. 
This PR upgrades the version used to 0.12.0 which supports v1.27 k8s and above [See here for compatibility](https://github.com/kubernetes-sigs/controller-tools?tab=readme-ov-file#compatibility).  This should be acceptable given it is already an unsupported version [See here for k8s supported versions](https://kubernetes.io/releases/)
=> Update controller-gen version to v0.12.0

argo/common/run_completion.go, controllers/webhook/runcompletion_event_trigger.go, controllers/webhook/runcompletion_event_trigger_unit_test.go, triggers/run-completion-event-trigger/cmd/functional_test.go, triggers/run-completion-event-trigger/internal/converters/converters.go, triggers/run-completion-event-trigger/internal/converters/converters_unit_test.go
Closes #402.
Ensures `ServingModelArtifacts` and `Artifacts` return an empty slice rather than nil.
Modified the helper functions which convert to and from the Artifact protobuf message. Converting from the protobuf definition in the run completion event trigger was the necessary function to change, but decided to keep both functions consistent with each other.
=> Ensure run completion events with no artifacts return an empty slice rather than nil

.tool-versions, DEVELOPMENT.md, Makefile, README.md, local/values.yaml, minikube.mk
Connects to #380 
- Added make targets that do the following:
- `minikube-up` 
- Starts a minikube cluster called `local-kfp-operator`
- Installs dependencies on the cluster required for KFP Operator
- Installs the operator itself
- Installs a provider based on the `NAME` parameter given the the make target
- Runs a `provider-setup.sh` script (if it exists) to perform any additional required steps for the chosen provider
- `minikube-down`
- Deletes the minikube cluster that was created by `minikube-up`
- Runs a `provider-teardown.sh` script (if it exists) to perform any clean up steps for the chosen provider
=> Added make targets for running KFP Operator locally in minikube

provider-service/base/pkg/streams/sources/pub_sub_source.go
In the PubSub source for the Provider service, we currently check that the subscription we initialise the source with exists before subscribing to the topic.
The problem is that we effectively interpret all errors as Not Found. This can obviously cause confusion while debugging by masking the real error.
=> Log all errors when fetching PubSub subscriptions

.github/ISSUE_TEMPLATE/feature_request.md
This is a small aesthetic change, but I believe using proper headings instead of bold text looks more structured and is more consistent with what I'd expect the formatting of a GitHub issue to look like.
=> Update feature request issue template

provider-service/kfp/Dockerfile, provider-service/vai/Dockerfile
Closes #450 
Updates the default path used within docker image for providers to be generic and match path used by viper within config loading. Fixes issue where if no config is explicitly mounted to the correct path the default config is not loaded and the container fails to start up.
=> Update default path to generic `/etc/provider-service`

config/manager/controller_manager_config.yaml, controllers/pipelines/provider_controller.go, controllers/pipelines/provider_controller_test.go, helm/kfp-operator/templates/configmap.yaml
Closes #461
This adds support to the provider controller to update provider CRD observedGeneration status field after reconciliation has 
completed successfully. This is required to provide tooling an indication that a given change causing a `Generation`  to increment has been reconciled by the controller of if it is out of sync.
=> Provider controller synchronise observedGeneration fields

apis/config/v1alpha6/kfp_controller_config_types.go, config/crd/bases/config.kubeflow.org_kfpcontrollerconfigs.yaml, config/manager/controller_manager_config.yaml, config/rbac/kustomization.yaml, config/rbac/role_binding.yaml, config/rbac/service_manager_role.yaml, controllers/pipelines/internal/workflowfactory/suite_integration_test.go, controllers/pipelines/provider_controller.go, controllers/pipelines/provider_controller_test.go, helm/kfp-operator/templates/configmap.yaml, helm/kfp-operator/templates/crd/bases/config.kubeflow.org_kfpcontrollerconfigs.yaml, helm/kfp-operator/templates/rbac/role_binding.yaml, helm/kfp-operator/templates/rbac/service_manager_role.yaml, provider-service/base/pkg/testutil/testutil.go, provider-service/kfp/internal/provider/pipeline_service_test.go, provider-service/kfp/internal/provider/pipeline_upload_service.go
Closes #463 
Manage a k8s service from the provider controller. This links up to the provider deployments ports for api access for workflows from within the cluster.
=> Add controller managed service for provider deployment

config/manager/workflows/compiled.yaml, helm/kfp-operator/templates/workflows/compiled.yaml
Connected to #464 
Introduce compile-files template and compile-files step to create/update compiled argo templates that will combine resource-definition.yaml and resource.json
The output artifact will be used later on for the workflow to call the provider-service API (not on this change).
=> compile-files argo template and step

version.mk
Closes #502.
Fix abbrev length to 8 to solve getting different versions on different machines
=> Version length - set to fixed length of 8 characters

provider-service/kfp/Makefile, provider-service/vai/Makefile
Closes #491
Remove DOCKER_BUILD_EXTRA_PARAMS from kfp and vai provider service makefiles because they are not used to pass into the docker-targets.mk's docker-build target
=> Cleanup provider service docker config

argo/providers/base/provider.go, config/manager/workflows/common.yaml, config/manager/workflows/compiled.yaml, config/manager/workflows/simple.yaml, controllers/pipelines/internal/workflowfactory/resource_workflow_factory.go, controllers/pipelines/provider_controller.go, helm/kfp-operator/templates/workflows/common.yaml, helm/kfp-operator/templates/workflows/compiled.yaml, helm/kfp-operator/templates/workflows/simple.yaml
Closes #519 
Changes all resources passed into workflows to be in JSON format, instead of YAML.
=> Use consistent JSON format across all workflow parameters

config/manager/workflows/common.yaml, helm/kfp-operator/templates/workflows/common.yaml
Connected to #512 and #511 
Remove select-provider-parameter argo workflow template. Remove select-provider-image and select-provider-sa steps from delete argo workflow template, which was left out of the above connected PR by mistake.
=> Remove select-provider-parameter argo workflow template and all related steps

helm/kfp-operator/templates/workflows/common.yaml
Closes #545.
Matches kustomize as metadata was {}
=> Empty metadata in common delete step is incorrect

provider-service/vai/internal/provider/job_enricher.go, provider-service/vai/internal/provider/job_enricher_test.go, provider-service/vai/internal/provider/provider.go
The pipeline schema handler wasn't getting initialised correctly in the builder causing panic. Also bug noticed that labels from pipeline definition were replacing what was on the job rather than merging the two
=> Initialise struct correctly for multi schema handling

provider-service/vai/internal/provider/job_builder.go, provider-service/vai/internal/provider/job_builder_test.go
Closes #557.
Realised that on submitting a new reconfiguration with a schedule to VAI for a KFP-SDK compiled pipeline definition that doesn't set the GCS storage value it fails to submit.
Corrected logic to set for both one off run and run schedule submit.
=> Add GcsOutputDirectory for scheduled job submission in VAI provider

.github/dependabot.yml
Closes #582
Limit dependabot to only raise pull requests for direct dependencies, and only target patch versions for now because most minor upgrades still require a go version upgrade (1.22.x -> 1.23.x), which is something that cannot be done yet.
=> Limit dependabot to only raise pull requests for direct dependencies and patch versions

.github/dependabot.yml
Closes #582
As per the [dependabot docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#ignore--), correct the update-type (invalid) setting of dependabot to be under the ignore field and call it correctly (update-types)
=> Correct the update-type setting of dependabot to be under the ignore field

argo/common/go.mod, argo/common/go.sum, argo/providers/go.mod, argo/providers/go.sum, common/go.mod, common/go.sum, provider-service/base/go.mod, provider-service/base/go.sum, provider-service/stub/go.mod, provider-service/stub/go.sum, provider-service/vai/go.mod, triggers/run-completion-event-trigger/cmd/main.go, triggers/run-completion-event-trigger/internal/server/server.go, triggers/run-completion-event-trigger/internal/server/server_unit_test.go
Closes #595
According to [golang docs](https://pkg.go.dev/context) the context is not supposed to be stored in structs and reused per request. Stop storing the context in trigger server and use the request context itself to initialise the per-request logger.
=> Decouple context from trigger server struct

.github/dependabot.yml
Closes #617
Set dependabot rebase-strategy to `disabled` to prevent a large number of pipelines being run every time something is merged.
=> Set dependabot rebase-strategy to `disabled`

argo/providers/go.work.sum, controllers/webhook/errors.go, controllers/webhook/event_processor.go, controllers/webhook/event_processor_unit_test.go, controllers/webhook/runcompletion_event_handler.go, controllers/webhook/runcompletion_event_trigger.go, controllers/webhook/runcompletion_event_trigger_unit_test.go, controllers/webhook/runcompletion_feed.go, controllers/webhook/runcompletion_feed_decoupled_test.go, controllers/webhook/runcompletion_feed_unit_test.go, controllers/webhook/status_updater.go, controllers/webhook/status_updater_unit_test.go, controllers/webhook/test_utils.go, main.go, provider-service/base/pkg/stream_message.go, provider-service/base/pkg/streams/sinks/webhook_sink.go, provider-service/base/pkg/streams/sinks/webhook_sink_decoupled_test.go, provider-service/base/pkg/streams/sinks/webhook_sink_unit_test.go, provider-service/base/pkg/streams/sources/pub_sub_source.go, provider-service/base/pkg/streams/sources/pub_sub_source_integration_test.go, provider-service/base/pkg/streams/sources/workflow_source.go, provider-service/kfp/go.work.sum, provider-service/kfp/internal/event/event_decoupled_test.go, provider-service/kfp/internal/event/event_flow.go, provider-service/stub/go.work.sum, provider-service/vai/go.work.sum, provider-service/vai/internal/runcompletion/event_flow.go, provider-service/vai/internal/runcompletion/event_flow_unit_test.go
Closes #493 
If the webhook (run completion feed http server) cannot find a resource (`Run` or `RunConfiguration`) for an event, it returns a `410` http code, indicating the resource is gone and not coming back (e.g. it's been deleted or was never in the cluster in the first place).
The current setup for how messages get handled in the Pub/Sub source is:
- Success: `ACK`
- Failure: `NACK`
This PR changes this setup to:
- Success: `ACK`
- Unrecoverable failure: `ACK`
- Recoverable failure: `NACK`
The only unrecoverable failure we're introducing is the `410` case so, for now, Pub/Sub messaged get `ACK`ed in the case of success or `410` and `NACK`ed otherwise. This means that Pub/Sub won't resend the message if a resource is missing, but it will in all other failure scenarios.
This work is …
=> Handle missing Runs / RunConfigurations in operator webhook

controllers/webhook/runcompletion_event_trigger.go, triggers/run-completion-event-trigger/cmd/main.go
Closes #626
Fix run completion event trigger service not showing per-request logging due to a regression introduced in https://github.com/sky-uk/kfp-operator/pull/594.
In that previous change, the top level context (which had the logger) was no longer being passed into the server, which was using it on a per request basis. This is because contexts should be derived on a per request basis, however when deriving the logger from the new per-request context, this broke logging since that new context did not have a logger.
In this change: introduce a unary server interceptor that will still use a new context per quest in line with golang best practices, but this time it will attach the top level logger into the context which restores logging.
=> Fix run completion event trigger service not showing per-request logging

apis/conditions.go, controllers/pipelines/runconfiguration_controller.go
Closes #625
The run configuration controller will sometimes get stuck in an infinite loop of reconciling a resource. This happens when a `Condition.LastTransitionTime` is being set by `SetSynchronizationState` and then immediately being compared with the in memory resource, which by definition will be different. This triggers a reconcile; in particular `MergeConditionsInto` is checking `LastTransitionTime` changes.
This change will remove `LastTransitionTime` from `MergeConditionsInto`, which means the controller will not reconcile just because that field was set.
=> Ignore runconfiguration reconcile condition LastTransitionTime

provider-service/vai/cmd/main.go, provider-service/vai/internal/label/label.go, provider-service/vai/internal/provider/label_gen.go, provider-service/vai/internal/provider/label_gen_test.go, provider-service/vai/internal/provider/provider.go
Closes #618 .
Adds extra labels when submitting resources to VAI, detailing which provider the resource was submitted from. This will be useful when dealing with multiple providers, as you will be able to filter logs and route logs using the provider label.
=> Add new provider label to vai provider - including namespace and name

apis/pipelines/hub/pipeline_types.go, apis/pipelines/hub/pipeline_types_test.go, apis/test/cross_version_pipeline_hash_test.go
In compute version we have started to return nil in the short term whilst handling the version upgrade to v1beta1 and not wanting to trigger pipeline compiles for all deployed pipelines. With an invalid resource it is possible to cause the nil to be returned which at the moment would cause a crash loop backoff of the controller manager.
With this change the manager doesn't crash.
Also added some extra tests around the compute hash function for pipeline.
=> Handle Pipeline hub ComputeHash returning nil

controllers/pipelines/runconfiguration_controller.go, controllers/pipelines/runconfiguration_controller_test.go
Closes #667.
A small and simple improvement, that gives the users some indication what a runconfiguration is waiting for when updating.
It simply populates the currently empty `message` field with a helpful message providing context on what it is doing.
=> Improve run-configuration status feedback when updating

provider-service/base/go.mod, provider-service/base/pkg/server/provider_server.go, provider-service/stub/go.mod, provider-service/stub/go.sum
Closes #421 
Add per-route metrics to all of the provider service's CRUD routes. Implementation uses the `otelhttp` middleware's metrics and injects a `http_route` label that identifies the route. Any `id`s will be ignored to keep the label cardinality under control.
=> Add metrics to provider server crud routes

compilers/kfp-sdk/acceptance/test_compiler.py, compilers/kfp-sdk/compiler/compiler.py, compilers/kfp-sdk/tests/test_compiler.py, compilers/tfx/compiler/compiler.py, compilers/tfx/tests/test_compiler.py
Closes https://github.com/sky-uk/kfp-operator/issues/721
Pipeline root storage is being set at submission time to the provider service, so no longer needs to be accessed and passed to `pipeline.Pipeline()` or to `Compiler().compile()`.
This also removes the extra beamArg of `--temp_location` in the TFX compiler which was being hardcoded by the compiler to be: `<pipelineRootStorage>/<pipeline>/tmp`. Users are now expected to set this beamArg themselves, either in the a Pipeline's `.spec.framework.parameters.beamArgs` or apply a default in a Provider's `.spec.frameworks[].patches` like so:
```
apiVersion: pipelines.kubeflow.org/v1beta1
kind: Provider
metadata:
name: my-provider
spec:
frameworks:
- name: tfx
image: kfp-operator-tfx-compiler:latest
patches:
- payload: …
```
=> Remove pipelineRootStorage access in compilers

compilers/README.md
Remove references to provider_config from the compilers documentation, which should have been removed in c0fbdee1f2aebba13f7c258fa2c9ed8427f77a07
=> Remove references to provider_config from the compilers documentation

.github/dependabot.yml
Update dependabot config to:
- only target the `kfpsdk-quickstart` python dependencies
- no longer target directories where there used to be separate go modules that were removed in d7f686d30177d32ceecb81bb61e81ee42c340d35
=> chore(dependabot): only target kfpsdk-quickstart dir for python dependencies and do not target dirs that no longer have gomod

provider-service/vai/internal/provider/job_builder.go, provider-service/vai/internal/provider/job_builder_test.go
This ensures that GCS storage locations are consistent between one-off runs and scheduled runs.
Closes #733
=> Use Pipeline name rather than Run name when setting GcsOutputDirectory

provider-service/base/pkg/server/resource/provider.go, provider-service/base/pkg/testutil/testutil.go
Closes #790
Rename PipelineDefinitionWrapper.PipelineDefinition.Framework.Type to PipelineDefinitionWrapper.PipelineDefinition.Framework.Name for uniformity.
=> Rename Framework.Type Framework.Name to match equivalent PipelineFramework in the argo package

README.md
Noticed that the root level README was out of date, as it didn't include support for KDP SDK
=> add KFP SDK support to top level README

apis/conditions.go, controllers/pipelines/provider_service_manager.go, go.mod, go.sum
Remove dependency on golang.org/x/exp - the old dependencies are now part of the stdlib.
=> Remove dependency on golang.org/x/exp
